filein( getFilenamePath(getSourceFileName()) + "/Menu/Menu.ms" )	--"./Menu/Menu.ms"
filein( getFilenamePath(getSourceFileName()) + "/RcMenu/RcMenu.ms" )	--"./RcMenu/RcMenu.ms"
filein( getFilenamePath(getSourceFileName()) + "/QuadMenu/QuadMenu.ms" )	--"./QuadMenu/QuadMenu.ms"
filein( getFilenamePath(getSourceFileName()) + "/QuadMenuManager/QuadMenuManager.ms" )	--"./QuadMenuManager/QuadMenuManager.ms"