filein( getFilenamePath(getSourceFileName()) + "/Menu/Menu.ms" )	--"./Menu/Menu.ms"

filein( getFilenamePath(getSourceFileName()) + "/MenuItem/MenuItem.ms" )	--"./MenuItem/MenuItem.ms"
filein( getFilenamePath(getSourceFileName()) + "/QuadMenu/QuadMenu.ms" )	--"./QuadMenu/QuadMenu.ms"
filein( getFilenamePath(getSourceFileName()) + "/QuadMenuLoader/QuadMenuLoader.ms" )	--"./QuadMenuLoader/QuadMenuLoader.ms"