filein( getFilenamePath(getSourceFileName()) + "/ControlsBox/ControlsBox.ms" )

/** Controls
 */
struct Controls_v
(
	--__construct = #(  ),
	--
	--/* required */
	--/* dependency */
	--/* reference */
	--/* properties */
	--list	= #(),
	--
	--/** Button
	-- */
	--function button caption id: params:"" =
	--(
	--	_Control 	= Control_v caption:caption id:id params:params
	--	
	--	append list _Control
	--	
	--	_Control --return
	--), 
	--
	--
	--
	--private
	--
	--
	--/**  
	-- */
	--on create do
	--(
	--	
	--	
	--)
	--
)
