--/*------------------------------------------------------------------------------
--  VERTICAL ALIGN IN GROUPBOX
------------------------------------------------------------------------------*/	
--
--/* GROUPBOX LEFT COLUMN
--*/ 
--macroscript macroFileTest_group_box
--	category:	"MacroFileTest"
--	buttontext:	"[TEST]"
--	icon:	"type:Groupbox|across:2"
--(
--	format "EventFired	= % \n" EventFired
--	print "Item selected"
--)
--
--/* LISTBOX RIGHT COLUMN
--*/ 
--macroscript MacroFileTest_groupbox_test
--	category:	"MacroFileTest"
--	buttontext:	"Listbox test"
--	icon:	"type:listbox|across:2|height:3"
--(
--)
--
--/*------ CONTROLS IN GROUPBOX ------*/
--macroscript MacroFileTest_groupbox_test
--	category:	"MacroFileTest"
--	buttontext:	"IN GROUPBOX 1"
--	icon:	"Groupbox:GROUPBOX_TEST"
--(
--)
--	
--macroscript MacroFileTest_groupbox_test
--	category:	"MacroFileTest"
--	buttontext:	"IN GROUPBOX 2"
--	icon:	"Groupbox:GROUPBOX_TEST"
--(
--)
--	
--	
--	
--	