clearListener()

/*------------------------------------------------------------------------------
			
			
			
			HOW TO ETEND LIST IN ANODHER STRUCT
			
			
--------------------------------------------------------------------------------*/

struct ExtendList_v
(
	
	/* ListBody is defining these variables
	   
		this.keys	= #() 
		this.values	= #()
	*/
	include "Library/MAXSCRIPT-UI-framework/Lib/List/ListBody.ms"

	 
	on create do
	(

	)
	
)